services:
  proxy:
      image: traefik:v2.11
      command: --providers.docker
      ports:
        - 80:80
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./src/
          action: sync
          target: /usr/local/fastapi-sandbox/src/
        - path: requirements.txt
          action: rebuild
          target: /usr/local/fastapi-sandbox/requirements.txt
    labels:
      traefik.enable: true
      traefik.http.routers.fastapi.rule: Host(`localhost`)
      traefik.http.services.fastapi.loadbalancer.server.port: 8000
